dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - coverage run --source flowqc --omit="flowqc/tests/*" run_tests.py

after_success:
  - codecov